# Generated by Django 3.1.7 on 2021-10-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('FloorId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('FloorName', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('MachineId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MachineName', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('RoomId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('RoomName', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floors')),
            ],
        ),
        migrations.CreateModel(
            name='TimeScheduleRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rooms')),
            ],
            options={
                'ordering': ['startTime'],
            },
        ),
        migrations.CreateModel(
            name='TimeScheduleMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floors')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machines')),
            ],
            options={
                'ordering': ['startTime'],
            },
        ),
        migrations.CreateModel(
            name='TimeScheduleFloor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floors')),
            ],
            options={
                'ordering': ['startTime'],
            },
        ),
        migrations.AddField(
            model_name='machines',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rooms'),
        ),
    ]
