# Generated by Django 3.2.8 on 2021-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField()),
                ('data', models.JSONField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeschedulemachine',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='timeschedulemachine',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='timescheduleroom',
            name='room',
        ),
        migrations.DeleteModel(
            name='TimeScheduleFloor',
        ),
        migrations.DeleteModel(
            name='TimeScheduleMachine',
        ),
        migrations.DeleteModel(
            name='TimeScheduleRoom',
        ),
    ]
