# Generated by Django 3.2.8 on 2021-10-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='costperunit',
            field=models.DecimalField(decimal_places=2, default=6.5, max_digits=3),
        ),
    ]
